# Generated by Django 4.2.2 on 2023-06-21 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('name', models.CharField(max_length=200, unique=True)),
                ('category_image', models.ImageField(upload_to='category_images')),
                ('about', models.TextField(max_length=250)),
                ('offer', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('name', models.CharField(max_length=200, unique=True)),
                ('product_images1', models.ImageField(blank=True, null=True, upload_to='product_images')),
                ('product_images2', models.ImageField(blank=True, null=True, upload_to='product_images')),
                ('product_images3', models.ImageField(blank=True, null=True, upload_to='product_images')),
                ('product_images4', models.ImageField(blank=True, null=True, upload_to='product_images')),
                ('product_images5', models.ImageField(blank=True, null=True, upload_to='product_images')),
                ('selling_price', models.IntegerField(default=0)),
                ('offer_price', models.IntegerField(default=0)),
                ('about', models.TextField(max_length=250)),
                ('offer', models.BooleanField(default=False)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
