# Generated by Django 4.2.2 on 2023-06-23 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='features',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.RenameModel(
            old_name='Category',
            new_name='MainCategory',
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('name', models.CharField(max_length=200, unique=True)),
                ('category_image', models.ImageField(upload_to='subcategory_images')),
                ('about', models.TextField(max_length=250)),
                ('offer', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.maincategory')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.subcategory'),
        ),
    ]
