# Generated by Django 4.2.2 on 2023-06-26 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_customer_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='district',
            field=models.CharField(choices=[('kasrgod', 'kasrgod'), ('Kannur', 'Kannur'), ('Wayanad', 'Wayanad'), ('Kozhikode', 'Kozhikode'), ('Malappuram', 'Malappuram'), ('Palakkad', 'Palakkad'), ('Thrissur', 'Thrissur'), ('Ernakulam', 'Ernakulam'), ('Idukki', 'Idukki'), ('Kottayam', 'Kottayam'), ('Alappuzha', 'Alappuzha'), ('Pathanamthitta', 'Pathanamthitta'), ('Kollam', 'Kollam'), ('Thiruvanathapuram', 'Thiruvanathapuram')], max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='house_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='place',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Andaman & nicobar islands', 'Andaman & nicobar islands'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Chandigarh', 'Chandigarh'), ('Chattisgarh', 'Chattisgarh'), ('Dadra & Nagar Haveli', 'Dadra & Nagar Haveli'), ('Daman and diu', 'Daman and diu'), ('Delhi', 'Delhi'), ('Delhi', 'Delhi'), ('Goa', 'Goa'), ('Gujarat', 'Gujarat'), ('Hariyana', 'Hariyana'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Jammu & kashmir', 'Jammu & kashmir'), ('Jharkhand', 'Jharkhand'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Lakshdweep', 'Lakshdweep'), ('Madhya dPradesh', 'Madhya dPradesh'), ('Maharashtra', 'Maharashtra'), ('Manipur', 'Manipur'), ('Meghalaya', 'Meghalaya'), ('Missoram', 'Missoram'), ('Nagaland', 'Nagaland'), ('Odisa', 'Odisa'), ('Puducherry', 'Puducherry'), ('Punjab', 'Punjab'), ('Rajasthan', 'Rajasthan'), ('Sikkim', 'Sikkim'), ('Tamilnadu', 'Tamilnadu'), ('Telengana', 'Telengana'), ('Tripura', 'Tripura'), ('Utharakhand', 'Utharakhand'), ('Utter pradesh', 'Utter pradesh'), ('West bengal', 'West bengal')], max_length=150, null=True),
        ),
    ]
