# Generated by Django 4.2.2 on 2023-07-04 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_images2',
            field=models.ImageField(blank=True, null=True, upload_to='product_images2'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_images3',
            field=models.ImageField(blank=True, null=True, upload_to='product_images3'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_images4',
            field=models.ImageField(blank=True, null=True, upload_to='product_images4'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_images5',
            field=models.ImageField(blank=True, null=True, upload_to='product_images5'),
        ),
    ]
